### ISSUE TITLE
Add `toDict`

### ISSUE THREAD

**Issue by Janiczek** [pzp1997/assoc-list#7]
This would be useful to me but I didn't find it in assoc-list nor in assoc-list-extra.

Something like:
```elm
toDict : Dict comparable a -> Dict.Dict comparable a
toDict assocList =
    Dict.fromList (toList assocList)
```

**Comment by pzp1997** [comment]
My initial thought on this is that if you have an assoc-list with `comparable` keys you probably should have been using an elm/core `Dict` in the first place.

Could you describe a use-case where this function would be useful? I'm thinking maybe if you have an assoc-list that has keys of type `a` that you then map over with an `a -> comparable` function but even so, I would think it would be cleaner in most cases to first apply the map and then build an elm/core Dict from the resulting `comparable` keys.

**Comment by Janiczek** [comment]
I am building a data structure library (BiDict) that has two variants: normal one (`BiDict comparable1 comparable2`) and assoc-list one (let's say `AssocBiDict a b`). I'm writing a fuzz test where I check that they both behave the same. Thus I have `AssocBiDict String Int` and `BiDict String Int` side by side, do the same things to them, check they are "the same". Hence my need for `AssocList.toDict` - I have `AssocList.Dict String Int` and I want to create `Dict String Int` from it.

**Comment by pzp1997** [comment]
First, I want to say that I really like the idea of your package.

Your proposed use for `AssocList.toDict` seems legitimate to me, although I would consider it a bit niche. I am hesitant about adding this function since I believe it could create confusion for beginners who might unnecessarily build an assoc-list only to ultimately convert it to a Dict when in fact it would be better to only use a Dict. Additionally, given that you can achieve the same effect as `AssocList.toDict` with a simple composition of two functions (`AssocList.toList` and `Dict.fromList`, as you showed above), I am less inclined to add a dedicated function for it.

I'm going to close this issue, but if you feel strongly about adding this function to some package, I would encourage you to make a proposal on [assoc-list-extra](https://github.com/skyqrose/assoc-list-extra/issues/new).

**Comment by Janiczek** [comment]
Thanks for the rationalization! Yes it's enough for me to use that `toList >> fromList` helper, defined myself. Thanks for considering this :)
